# Rmarkdown showing how to get the efficacy estimates for various RSV products

## Load relevant packages

```{r}

library(cmdstanr)
library(tidyverse)
library(posterior)
library(tidybayes)
library(patchwork)
library(here)

source(here::here("R", "utils.R") )

```

# Load data and find lower bounds for stan model

```{r}

# Loads information about Kaplan-Meier plots 
source(here::here("R", "get_times.R") )

# Finding the optimal value for the shape parameter of the exponential, Erlang-2, and Ergland-3 distributions
expfunc <- function(x) (pexp(365, x) - 0.95) ^ 2
erl2func <- function(x, k) ((1 - pgamma(365, 2, x)) - 0.05) ^ 2;
erl3func <- function(x, k) ((1 - pgamma(365, 3, x)) - 0.05) ^ 2;

# Find the lower bounds such that non of the distributions have more than 5% of the probability mass after 365 days
lower_bound_wane_exp <- optim(c(0.01), lower = 0.0001, upper = 0.1, expfunc, method = "Brent")$par
lower_bound_wane_erl2 <- optim(c(0.01), lower = 0.0001, upper = 0.1, erl2func, method = "Brent")$par
lower_bound_wane_erl3 <- optim(c(0.01), lower = 0.0001, upper = 0.1, erl3func, method = "Brent")$par

lower_bounds_95_loss <- 1 / c(lower_bound_wane_exp, lower_bound_wane_erl2, lower_bound_wane_erl3)

# These are the values need if there are no boundary conditions (used in the rsvie package)
lower_bounds_no_boundary <- c(365, 180, 120)

data_nmab <- get_nmab_data()
data_nmab$placebo <- data_nmab$placebo %>%
    mutate(week = rep(1:22, each = 7)[1:150]) %>%
    group_by(week) %>%
    summarise(t = mean(t), person_time = mean(person_time), n = sum(n)) %>%
    mutate(tp = week)

data_nmab$vaccine <- data_nmab$vaccine %>%
    mutate(week = rep(1:22, each = 7)[1:150]) %>%
    group_by(week) %>%
    summarise(t = mean(t), person_time = mean(person_time), n = sum(n)) %>%
    mutate(tp = week)
data_matvac <- get_matvac_data()
data_oa_papi <- get_oa_papi_data()
data_oa_walsh <- get_oa_walsh_data()


```

## Run the stan model

```{r}

# Npte: If you run into errors with the build, delete the src/eff_est file (NOT the eff_est.stan) and try running `rebuild_cmdstan()`

source(here::here("R", "model.R") )

fitted_functions(data_nmab, "nmab_bounded", lower_bounds_95_loss)
fitted_functions(data_matvac, "mat_bounded", lower_bounds_95_loss)
fitted_functions(data_oa_papi, "oa_papi_bounded", lower_bounds_95_loss)
fitted_functions(data_oa_walsh, "oa_walsh_bounded", lower_bounds_95_loss)

fitted_functions(data_nmab, "nmab_nobound", lower_bounds_no_boundary)
fitted_functions(data_matvac, "mat_nobound", lower_bounds_no_boundary)
fitted_functions(data_oa_papi, "oa_papi_nobound", lower_bounds_no_boundary)
fitted_functions(data_oa_walsh, "oa_walsh_nobound", lower_bounds_no_boundary)

```

## Create the comprison plots

```{r}

source(here::here("R", "plots.R") )

data_eff_mat <- data.frame(
        days = c(90, 120, 150, 180),
        mean = c(57.1, 56.8, 52.5, 51.3) / 100,
        lb_95 = c(14.7, 31.2, 28.7, 29.4) / 100,
        ub_95 = c(79.8, 73.5, 68.9, 66.8) / 100,
        type = "Observed efficacy"
    )


plot_outputs(data_eff_mat, "mat_nobound")
plot_outputs(data_eff_mat, "mat_bounded")

data_eff_nmab <- data.frame(
        days = c(150),
        mean = c(79.5) / 100,
        lb_95 = c(65.9) / 100,
        ub_95 = c(87.1) / 100,
        type = "Observed efficacy"
    )


plot_outputs(data_eff_nmab, "nmab_nobound")
plot_outputs(data_eff_nmab, "nmab_bounded")

data_eff_lav <- data.frame(
        days = c(180),
        mean = c(66.7) / 100,
        lb_95 = c(28.8) / 100,
        ub_95 = c(85.8) / 100,
        type = "Observed efficacy"
    )

plot_outputs(data_eff_lav, "oa_papi_nobound")
plot_outputs(data_eff_lav, "oa_papi_bounded")

```

```{r}

# get point estimates for the efficacy
modelname <- "mat_nobound"
day_no <- 365
post_mat_get <- load(file = here::here("outputs", modelname, paste0(modelname, "_post_wane.Rdata")))
efficacy_mat <- get(post_mat_get) 
c(
    1:4000 %>% map_dbl(~efficacy_mat$wane_a_er3[.x] * (1 - pgamma(day_no, 3, 1/efficacy_mat$wane_b_er3[.x])) ) %>% mean,
    1:4000 %>% map_dbl(~efficacy_mat$wane_a_er3[.x] * (1 - pgamma(day_no, 3, 1/efficacy_mat$wane_b_er3[.x])) ) %>% quantile(c(0.025, 0.975))
)

modelname <- "nmab_nobound"
day_no <- 365
post_mat_get <- load(file = here::here("outputs", modelname, paste0(modelname, "_post_wane.Rdata")))
efficacy_mat <- get(post_mat_get) 
c(
    1:4000 %>% map_dbl(~efficacy_mat$wane_a_er3[.x] * (1 - pgamma(day_no, 3, 1/efficacy_mat$wane_b_er3[.x])) ) %>% mean,
    1:4000 %>% map_dbl(~efficacy_mat$wane_a_er3[.x] * (1 - pgamma(day_no, 3, 1/efficacy_mat$wane_b_er3[.x])) ) %>% quantile(c(0.025, 0.975))
)

modelname <- "oa_papi_nobound"
day_no <- 180
post_mat_get <- load(file = here::here("outputs", modelname, paste0(modelname, "_post_wane.Rdata")))
efficacy_mat <- get(post_mat_get) 
c(
    1:4000 %>% map_dbl(~efficacy_mat$wane_a_er3[.x] * (1 - pgamma(day_no, 3, 1/efficacy_mat$wane_b_er3[.x])) ) %>% mean,
    1:4000 %>% map_dbl(~efficacy_mat$wane_a_er3[.x] * (1 - pgamma(day_no, 3, 1/efficacy_mat$wane_b_er3[.x])) ) %>% quantile(c(0.025, 0.975))
)



```



# Save new estimates in rsvie workflow

```{r}

save_model <- function(modelname) {
    post_mat_get <- load(file = here::here("outputs", modelname, paste0(modelname, "_post_wane.Rdata")))
    efficacy_mat <- get(post_mat_get) 
    efficacy_mat <- as.data.frame(efficacy_mat)
    saveRDS(efficacy_mat, file = paste0("/Users/davidhodgson/Dropbox/Mac (3)/Documents/research/rsv/rsvmatmab/data/efficacies/", modelname, "_wane.rds") )
}

save_model("mat_nobound")
save_model("mat_bounded")

save_model("nmab_nobound")
save_model("nmab_bounded")

save_model("oa_papi_nobound")
save_model("oa_papi_bounded")

```